# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CouchbaseSyncDemo' do
     pod 'couchbase-lite-ios', '~> 1.0'
end

target 'CouchbaseSyncDemoTests' do

end

